### ISSUE TITLE
mydumper compilation issue and incorrect version

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1550]
Hello, 

In `/var/opt/mydumper-0.10.1/CMakeLists.txt`, the version is set to 0.10.0, not 0.10.1 so it will always try to rebuild on upgrade `set(VERSION 0.10.0)`

Also, I've been encountering a compile error similar to https://github.com/maxbube/mydumper/issues/29. The workaround provided to add `-lm` to the `target_link_libraries()` lines works for me. My exact error is as follows:

```
/usr/bin/ld: CMakeFiles/mydumper.dir/mydumper.c.o: undefined reference to symbol 'ceilf@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/mydumper.dir/build.make:203: recipe for target 'mydumper' failed
make[2]: *** [mydumper] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mydumper.dir/all' failed
make[1]: *** [CMakeFiles/mydumper.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by omega8cc** [comment]
It should not be a problem anymore after version update in BOA head.
